baseURL = "https://wooworks.io/"
languageCode = "en-us"
title = "wooworks"
theme = "coder"

[pagination]
  pagerSize = 10

[params]
  author = "Woo"
  info = "Dev, Designer, Writer"
  description = "This is my personal blog built with Hugo and the Coder theme."
  keywords = "인디메이커,developer,personal"
  avatarURL = "images/avatar.jpg" # 없어도 됨

[[params.social]]
  name = "GitHub"
  icon = "fa fa-github"
  url = "https://github.com/yourusername"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2